# Numpy

For technical reasons, pure Python is not fast enough for numerical data analysis.
To work around this problem various packages were developed.
Most packages are based on the API, which was developed and implemented by [Numpy](https://www.numpy.org/).
Therefore we are concentrating in particular on numpy.

Numpy is a package to compute efficiently on multi-dimensional arrays (tensors) with Python.
It offers various features, some of them listed below:

-  types:
   -   numeric data types of different precisions
   -   ndarray: multi-dimensional array of a particular type.
   -   masked Arrays: array that may have missing values, e.g. for missing data or land masks
-  functions and methods:
   -   ufunc: operate element wise on arrays (+, -, sin, cos, ...)
   -   ndarray methoden: e.g. mean, sum, max, transpose, dot ...
   -   linear algebra (matrix inversion, etc.)
   -   ...
   
Before we can use numpy, we have to import it.

In [1]:
import numpy as np

## Ndarray

The [ndarray](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html) class is the foundation of numpy. A ndarray object represents a multidimensional and homogeneous array consisting of elements of fixed size. This means that all elements are of the same type.

### Creating Arrays
To create an ndarray object, the following functions are used:

-   [numpy.array](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html)
-   [numpy.zeros](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html)
-   [numpy.empty](https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty.html)
-   [numpy.ones](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)
-   [numpy.full](https://docs.scipy.org/doc/numpy/reference/generated/numpy.full.html)
-   [numpy.zeros_like](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros_like.html)
-   [numpy.empty_like](https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty_like.html)
-   [numpy.ones_like](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones_like.html)
-   [numpy.full_like](https://docs.scipy.org/doc/numpy/reference/generated/numpy.full_like.html)

```{margin}
The second example shows, that all elements of an array do have the same type.
When an array is created from a sequence of multiple types, all elements will be converted to a compatible type without data loss.
```

In [17]:
a1 = np.array([1, 2, 3])

a2 = np.array([1., 2, 3])

# Array containing only zeros
z = np.zeros((3, 2))

# Array containing only ones
o = np.ones((5, 3))

# Array containing only zeros with the same metadata as o
zeros_from_ones = np.zeros_like(o)

# Array without initial values
buffer = np.empty((3, 2))

# 10x10 identity matrix
a = np.eye(10)

# As range(), but also for floats
x1 = np.arange(1, 10, 0.1)

x2 = np.linspace(0, 2 * np.pi, 100)

y = np.sin(x1)

```{note}
Arrays can also be initialized via a sequence, such as a list or a tuple, or other iterable types, e.g. a range.
```

In [6]:
print(np.array(range(3)))

[0 1 2]


### Attributes

Arrays have attributes which contain its meta data. These attributes are:

-   `ndim`: Number of dimensions
-   `shape`: tuple of the length of the dimensions
-   `size`: number of all elements
-   `dtype`: data type of all elements
-   `itemsize`: size of the elements in bytes

In [23]:
a = np.array([[2, 3, 1], [5, 7, 3]])

print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

[[2 3 1]
 [5 7 3]]
2
(2, 3)
6
int64
8


### Indexing and Slicing

Indexing and slicing works in the same way as it does for sequences.

In [24]:
a = np.array(range(9), dtype=np.int)
print(a)
print(a[4])
print(a[1:3])
print(a[::-1])

[0 1 2 3 4 5 6 7 8]
4
[1 2]
[8 7 6 5 4 3 2 1 0]


Numpy array are `mutable` which means that we can change elements of an array after it has been created.

```{note}
When changing an element of an array, the data will be casted to the type of the array.
This may cause loss of information as shown below.
```

In [13]:
a = np.array(range(9))
print(a)

a[5] = 3.4
print(a)

[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 3 6 7 8]


```{warning}
Unlike for lists, slices of an numpy array are references to the slice of the original array.
Hence changing data of a slice also changes the original array!
```

In [15]:
a = np.array(range(9))

b = a[1:2]
b[0] = 20

print(b)
print(a)

[20]
[ 0 20  2  3  4  5  6  7  8]


Multi-dimensional arrays may have one index per axis. Tuples of indices are automatically filled with `:` to the right.

In [30]:
a = np.random.random((2, 3, 4))

print(a)
print(a[1, 2, 1])
print(a[:, 1, 1])
print(a[1:, :, :])

print(a[-1])

[[[0.75927542 0.67008731 0.06948295 0.3219854 ]
  [0.8164175  0.89856409 0.48034308 0.85270738]
  [0.13092369 0.29600006 0.6499389  0.10710406]]

 [[0.2234761  0.95906661 0.68333508 0.70382561]
  [0.59257239 0.62352223 0.95006678 0.86956172]
  [0.06296639 0.27606878 0.12782001 0.62795607]]]
0.2760687789695674
[0.89856409 0.62352223]
[[[0.2234761  0.95906661 0.68333508 0.70382561]
  [0.59257239 0.62352223 0.95006678 0.86956172]
  [0.06296639 0.27606878 0.12782001 0.62795607]]]
[[0.2234761  0.95906661 0.68333508 0.70382561]
 [0.59257239 0.62352223 0.95006678 0.86956172]
 [0.06296639 0.27606878 0.12782001 0.62795607]]


Sometimes we may want to write code that does not assume a particular number of dimensions for the arrays.
Here, the `...` notation is useful. It is used as an dummy for as many `:` as necessary to fill the index tuple.

In [38]:
print(a[..., 0])
print(a[:2, ..., 1])

[[0.75927542 0.8164175  0.13092369]
 [0.2234761  0.59257239 0.06296639]]
[[0.67008731 0.89856409 0.29600006]
 [0.95906661 0.62352223 0.27606878]]


In [39]:
x = np.arange(2 * 3 * 2 * 5 * 4).reshape(2, 3, 2, 5, 4)

print((x[1, 2, ...] == x[1, 2, :, :, :]).all())
print((x[..., 3] == x[:, :, :, :, 3]).all())
print((x[1, ..., 4, :] == x[1, :, :, 4, :]).all())

True
True
True


### Iterating over arrays

We can iterate over the elements of an one-dimensional array in the same way as we do for lists.

In [25]:
a = np.arange(10) ** 3

for e in a:
    print(e ** (1 / 3.))

0.0
1.0
2.0
3.0
3.9999999999999996
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


Multi-dimensional arrays are iterated over with respect to the first axis.
If we are iterating over an array of shape `(2, 3)`, the `for` loop will consist of two iterations and the variable in within the loop body will be an array of shape `(3,)`.

In [43]:
a = np.arange(5 * 3).reshape((3, 5))
for row in a:
    print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]


To iterate over all elements of an array, the attribute `flat` can be used.

In [42]:
for element in a.flat:
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


### Reshape

Sometimes it is useful to change the shape of the array. Therefore numpy offers the following options:

-   The `shape` attribute of the array can be overwritten.
-   `transpose` returns the transposed array. The order of the axis is reversed.
-   [reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html) returns a reference to the same data having its shape changed.
-   [resize](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.resize.html) changes the size of the array itself and returns `None`.

```{note}
When changing the shape of an array, the new shape must be compatible with the old one. That is, there must fit the same number of elements in both shapes.
If the new shape is not compatible, a `ValueError` is raised.
```

In [50]:
a = np.arange(3 * 4).reshape((3, 4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [51]:
a.shape = (3, 2, 1, 2)
print(a)

[[[[ 0  1]]

  [[ 2  3]]]


 [[[ 4  5]]

  [[ 6  7]]]


 [[[ 8  9]]

  [[10 11]]]]


In [52]:
print(a.transpose())

[[[[ 0  4  8]
   [ 2  6 10]]]


 [[[ 1  5  9]
   [ 3  7 11]]]]


In [53]:
a.resize((2, 6))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [54]:
b = a.reshape((3, -1))
print(b.shape)

(3, 4)


In [55]:
# b references to the same data as a!
b[2, 2] = 100
print(a)

[[  0   1   2   3   4   5]
 [  6   7   8   9 100  11]]


### Operators

Numpy offers the same arithmetic and logic operators which we already know from the basic python data types.
These operators always work element wise.

In [59]:
a = np.arange(4)
b = np.array([2, 7, 4.5, 1])

In [60]:
print(a - b)

[-2.  -6.  -2.5  2. ]


In [61]:
print(a * b)

[0. 7. 9. 3.]


In [62]:
print(b ** 2)

[ 4.   49.   20.25  1.  ]


In [63]:
print(b ** a)

[ 1.    7.   20.25  1.  ]


In [64]:
print(a % 3)

[0 1 2 0]


In [65]:
print(10 * np.sin(a))

[0.         8.41470985 9.09297427 1.41120008]


In [66]:
print(b <= 4)

[ True False False  True]


In [67]:
# in-place addition
b += a
print(b)

[2.  8.  6.5 4. ]



In order to be able to perform element wise operations between two arrays, the shapes of these arrays must be compatible.
If they are not compatible, a `ValueError` is raised.

In [68]:
a = np.arange(3)
b = np.arange(2)
a + b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

Most unary operators (operators which have only one argument) are implemented as a method of the ndarray class.
In many cases it is possible to apply the operators along one or more specific axis via the `axis` keyword.

In [71]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [72]:
# sum of all elements
print(a.sum())

21


In [73]:
# sum along the first dimension
print(a.sum(axis=0))

[ 9 12]


In [74]:
# global minimum
print(a.min())

1


In [75]:
# global maximum
print(a.max())

6


In [76]:
# mean
print(a.mean())

3.5


In [77]:
# cummultative sum along the second dimension
print(a.cumsum(axis=1))

[[ 1  3]
 [ 3  7]
 [ 5 11]]


In [81]:
# dot product (actually a binary operator)
b = np.arange(2)
print(a.dot(b), np.dot(a, b))

[2 4 6] [2 4 6]


## Numpy functions

Numpy offers a huge set of functions covering almost all fundamental computational demands in science.
Many of these functions are grouped in modules within the numpy package.
The following list contains links to the official documentation.
Take some time to see what is offered.
There is a solution for many problems you will have to solve in the future.

-  [Array manipulation routines](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)
-  [Mathematical functions](https://numpy.org/doc/stable/reference/routines.math.html)
-  [Linear algebra](https://numpy.org/doc/stable/reference/routines.linalg.html)
-  [Random sampling](https://numpy.org/doc/stable/reference/random/index.html)
-  [Statistics](https://numpy.org/doc/stable/reference/routines.sort.html)
-  [Discrete Fourier Transform](https://numpy.org/doc/stable/reference/routines.fft.html)
-  [Logic functions](https://numpy.org/doc/stable/reference/routines.logic.html)
-  [Sorting, searching and counting](https://numpy.org/doc/stable/reference/routines.sort.html)
-  [Functional programming](https://numpy.org/doc/stable/reference/routines.functional.html)
-  [Input and output](https://numpy.org/doc/stable/reference/routines.io.html)

```{Note}
The better you know the numpy library the easier it will be for you to write scientific software, e.g. for analyzing and visualizing data.
```